### ISSUE TITLE
Is this method safe from hallucinating problem?

### ISSUE THREAD

**Issue by albertchristianto** [BCV-Uniandes/UltraGAN#1]
Hi, what an interesting project. 

Since I have a similar project with this repository, I have some questions regarding the hallucination problem in GAN and in the deep learning method.
https://www.wired.com/story/ai-has-a-hallucination-problem-thats-proving-tough-to-fix/ 
https://arxiv.org/pdf/1805.08841.pdf
https://arxiv.org/pdf/2012.00646.pdf 
What do you think about this problem? Have you tested your model from the hallucination problem that might exist?
If yes, What kind of method you are using to test the model from the hallucinating problem?

best regards,
Albert

**Comment by mc-escobar11** [comment]
Hi Albert, 

Thank you for your interest in our project. Hallucinations tend to be a great limitation in medical GANs and are the reason why we included the segmentation of anatomical structures in our discriminator. Using this dual discriminator allows us to make sure that the enhanced image does not differ in structure with the original. We use segmentation of anatomical structures as a proxy to measure how consistent is our generation process. 

Best, 
Maria
