### ISSUE TITLE
can not get dataset

### ISSUE THREAD

**Issue by May-dream** [BCV-Uniandes/UltraGAN#2]
Hello, I can't access that website and I can't get the dataset, could you please put the dataset used for this project in google drive for me to download? Thanks!
![image](https://user-images.githubusercontent.com/74846990/165219647-0b22d378-6608-4bc3-8a53-1d514c98b7e0.png)

**Comment by mc-escobar11** [comment]
Hello,  we are not allowed to share the dataset since it is not ours and we signed a NDA. I recommend you ask the creators of the dataset.
