### ISSUE TITLE
ModuleNotFoundError:No module named 'data.unaligned_dataset'

### ISSUE THREAD

**Issue by May-dream** [BCV-Uniandes/UltraGAN#3]
hello, when I run this project, I met a problem: ModuleNotFoundError:No module named 'data.unaligned_dataset' ,How can I solve the problem? thank you!
![微信图片_20220426230831](https://user-images.githubusercontent.com/74846990/165332480-4d14f617-036d-4188-b7ba-4610298e0f09.jpg)

**Comment by silviastra** [comment]
i have the same question, did you know how to deal with it?

**Comment by mc-escobar11** [comment]
hi, it should get fixed if you add the flag --dataset_mode unalignedseg to the training. Please check our train.sh to find the correct command for training
